"""
Chatbot Service
ChatterBot implementation for weather assistant
"""

try:
    from chatterbot import ChatBot
    from chatterbot.trainers import ListTrainer
    from chatterbot.logic import LogicAdapter
except ImportError:
    # Mock for development/when dependencies missing
    from unittest.mock import MagicMock
    ChatBot = MagicMock
    ListTrainer = MagicMock
    LogicAdapter = object  # Needs to be a class to inherit from

import logging
import re
from typing import Tuple, Optional, Dict, Any
from datetime import datetime

from services.weather_service import WeatherService
from utils.geocoding import geocode_city
from firestore_client import db

logger = logging.getLogger(__name__)

from utils.nlp_utils import extract_city_from_message, is_weather_query

class WeatherLogicAdapter(LogicAdapter):
    """
    Custom logic adapter for processing weather queries.
    """
    def __init__(self, chatbot, **kwargs):
        super().__init__(chatbot, **kwargs)
        self.weather_service = WeatherService()

    def can_process(self, statement):
        """
        Check if the statement contains weather-related keywords.
        """
        return is_weather_query(statement.text)

    def process(self, input_statement, additional_response_selection_parameters):
        from chatterbot.conversation import Statement
        
        # This adapter is mainly for detection; actual processing happens in the service
        # We return a high confidence score so the service knows it's weather-related
        # The actual response text will be generated by the service layer
        response = Statement(text="Let me check the weather for you.")
        response.confidence = 1.0
        return response


class ChatbotService:
    """
    Chatbot service using ChatterBot with custom weather logic.
    """
    
    _instance = None
    
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(ChatbotService, cls).__new__(cls)
            cls._instance._initialize_bot()
        return cls._instance
    
    def _initialize_bot(self):
        """
        Initialize and train the ChatterBot instance.
        """
        try:
            self.bot = ChatBot(
                'VornicsWeatherBot',
                storage_adapter='chatterbot.storage.SQLStorageAdapter',
                database_uri='sqlite:///database.sqlite3',
                logic_adapters=[
                    {
                        'import_path': 'services.chatbot_service.WeatherLogicAdapter'
                    },
                    'chatterbot.logic.BestMatch',
                    'chatterbot.logic.TimeLogicAdapter'
                ]
            )
            
            # Train with some basic weather conversations
            trainer = ListTrainer(self.bot)
            trainer.train([
                "Hi",
                "Hello! I'm Vornics AI. I can help you with weather updates.",
                "Hello",
                "Hi there! Ask me about the weather in any city.",
                "How are you?",
                "I'm doing great! Ready to check some weather data.",
                "What can you do?",
                "I can provide real-time weather updates, forecasts, and alerts for any location.",
                "Help",
                "Just type a city name or ask 'What's the weather in London?'",
                "Bye",
                "Goodbye! Stay safe and dry!",
            ])
            
            self.weather_service = WeatherService()
            logger.info("ChatterBot initialized and trained successfully")
            
        except Exception as e:
            logger.error(f"Failed to initialize ChatterBot: {e}")
            # Fallback or re-raise depending on requirements
            self.bot = None

    async def generate_response(
        self,
        message: str,
        user_id: str,
        session_id: str
    ) -> Tuple[str, Optional[Dict[str, Any]]]:
        """
        Process user message and generate response.
        
        1. Check if message contains city name
        2. If city found: fetch weather and return specific response
        3. If no city: use ChatterBot for generic response
        """
        try:
            city = extract_city_from_message(message)
            weather_data = None
            response_text = ""
            
            if city:
                try:
                    # Geocode and fetch weather
                    # We pass 'db' to enable caching in geocode_city if needed, 
                    # but here we might just rely on the service's internal logic
                    from firestore_client import db as firestore_db
                    geocode_data = await geocode_city(city, firestore_db)
                    
                    weather_response = await self.weather_service.get_current_weather(
                        geocode_data['lat'],
                        geocode_data['lon']
                    )
                    
                    # Simplify data for frontend
                    weather_data = {
                        "city": geocode_data['city'],
                        "temperature": weather_response.get('temperature'),
                        "condition": weather_response.get('condition'),
                        "humidity": weather_response.get('humidity'),
                        "windSpeed": weather_response.get('windSpeed')
                    }
                    
                    response_text = (
                        f"The current weather in {weather_data['city']} is {weather_data['condition']} "
                        f"with a temperature of {weather_data['temperature']}°C. "
                        f"Humidity is at {weather_data['humidity']}%."
                    )
                    
                except Exception as e:
                    logger.warning(f"Could not fetch weather for extracted city '{city}': {e}")
                    # Fallback to bot if weather fetch fails
                    response_text = str(self.bot.get_response(message))
            else:
                # No city found, use ChatterBot
                if self.bot:
                    response_text = str(self.bot.get_response(message))
                else:
                    response_text = "I'm currently offline. Please try again later."
            
            # Log conversation to Firestore (optional but recommended)
            # This is handled in the route handler usually, but we can do it here too if needed.
            # The route handler in chatbot_routes.py already saves the conversation.
            
            return response_text, weather_data

        except Exception as e:
            logger.error(f"Error processing chatbot message: {e}")
            return "I encountered an error processing your request.", None
